In [ ]:
%pip install polars

In [2]:
import polars as pl
df = pl.read_csv("../data/atlantis.csv")

In [6]:
df.head()

shape: (5, 2)
┌──────┬────────────┐
│ year ┆ population │
│ ---  ┆ ---        │
│ i64  ┆ i64        │
╞══════╪════════════╡
│ 2000 ┆ 12400      │
│ 2001 ┆ 12800      │
│ 2002 ┆ 13800      │
│ 2003 ┆ 13600      │
│ 2004 ┆ 14200      │
└──────┴────────────┘

In [7]:
df.tail()

shape: (5, 2)
┌──────┬────────────┐
│ year ┆ population │
│ ---  ┆ ---        │
│ i64  ┆ i64        │
╞══════╪════════════╡
│ 2017 ┆ 29600      │
│ 2018 ┆ 32100      │
│ 2019 ┆ 32500      │
│ 2020 ┆ 33200      │
│ 2021 ┆ 33800      │
└──────┴────────────┘

In [8]:
df.shape

(22, 2)

In [9]:
df.columns

['year', 'population']

In [10]:
df.dtypes

[Int64, Int64]

In [16]:
df.null_count()
df.is_duplicated().sum()

0

In [15]:
df.describe()

shape: (9, 3)
┌────────────┬──────────┬──────────────┐
│ statistic  ┆ year     ┆ population   │
│ ---        ┆ ---      ┆ ---          │
│ str        ┆ f64      ┆ f64          │
╞════════════╪══════════╪══════════════╡
│ count      ┆ 22.0     ┆ 22.0         │
│ null_count ┆ 0.0      ┆ 0.0          │
│ mean       ┆ 2010.5   ┆ 22418.181818 │
│ std        ┆ 6.493587 ┆ 7100.411548  │
│ min        ┆ 2000.0   ┆ 12400.0      │
│ 25%        ┆ 2005.0   ┆ 15600.0      │
│ 50%        ┆ 2011.0   ┆ 22400.0      │
│ 75%        ┆ 2016.0   ┆ 28300.0      │
│ max        ┆ 2021.0   ┆ 33800.0      │
└────────────┴──────────┴──────────────┘